-- Категории извлечённые из categories.ibd
-- Создано автоматически

USE enb;

-- Создание таблицы
CREATE TABLE IF NOT EXISTS categories (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    parent_id INT DEFAULT NULL,
    created_at INT,
    updated_at INT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Вставка данных
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (1, '/agrotovary/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (2, '/agroturizm/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (3, '/arenda-spetstekhniki/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (4, '/aviakhimraboty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (5, '/avtomobilnyy-skh-transport/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (6, '/bakaleya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (7, '/barda/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (8, '/bezalkogolnye-napitki-soki/"<', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (9, '/biopreparaty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (10, '/bioudobrenie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (11, '/chay-kofe-kakao/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (12, '/dekorativnye-kultury/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (13, '/dezinfitsiruyushhie-sredstva/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (14, '/emkostnoe-oborudovanie/2X', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (15, '/fasovochnoe-i-upakovochnoe-oborudovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (16, '/fermy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (17, '/frukty-yagody/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (18, '/griby/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (19, '/grunty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (20, '/gruzoperevozki/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (21, '/gsm/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (22, '/inform-agentstva/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (23, '/ingredienty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (24, '/investitsii-skh/+J', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (25, '/izolyaty-kontsentraty-teksturaty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (26, '/karkasno-tentovye-konstruktsii/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (27, '/khelatnye-mikroudobreniya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (28, '/khlebopekarnoe-i-konditerskoe-oborudovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (29, '/kholodilnoe-oborudovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (30, '/khozyaystvo/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (31, '/knigi/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (32, '/kombikorma/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (33, '/konditerskie-izdeliya/"4', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (34, '/konservy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (35, '/korma-dlya-ryb/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (36, '/korma-ekstrudirovannye/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (37, '/kormouborochnaya-tekhnika/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (38, '/kormovye-dobavki/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (39, '/kormovye-drozhzhi/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (40, '/kormovye-korneplody/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (41, '/krakhmalo-patochnaya-produktsiya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (42, '/krupy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (43, '/makaronnye-izdeliya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (44, '/markirovochnoe-i-etiketirovochnoe-oborudovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (45, '/maslichnye-kultury/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (46, '/maslozhirovaya-produktsiya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (47, '/med-produkty-pchelovodstva/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (48, '/mini-tekhnika/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (49, '/moechnoe-i-sanitarno-gigienicheskoe-oborudovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (50, '/molochnye-produkty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (51, '/muka-krovyanaya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (52, '/muka-perevaya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (53, '/muka-travyanaya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (54, '/muka/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (55, '/myasnaya-muka/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (56, '/myaso/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (57, '/myasokostnaya-muka/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (58, '/navigatsionnye-sistemy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (59, '/nekonditsionnaya-produktsiya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (60, '/oborudovanie-dlya-rastenievodstva/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (61, '/oborudovanie-dlya-rybovodstva/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (62, '/oborudovanie-dlya-traktorov/*D', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (63, '/oborudovanie-myaso/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (64, '/oborudovanie-otkhody/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (65, '/oborudovanie-ovoshhi-frukty/",', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (66, '/oborudovanie-pchelovodstvo/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (67, '/oborudovanie-pererabotka-moloka/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (68, '/oborudovanie-prochee/%&', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (69, '/oborudovanie-proizvodstvo-kormov/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (70, '/oborudovanie-ptitsevodstvo/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (71, '/oborudovanie-sklady/,O', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (72, '/oborudovanie-upakovka/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (73, '/oborudovanie-zhivotnovodstvo/!4', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (74, '/opryskivateli/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (75, '/orekhi/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (76, '/organo-mineralnye-udobreniya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (77, '/otkhody/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (78, '/otrubi/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (79, '/ovoshhi-i-frukty-sushenye/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (80, '/ovoshhi-i-frukty-zamorozhennye/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (81, '/ovoshhi/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (82, '/pasty-pyure/"<', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (83, '/pererabatyvayushhie-predpriyatiya/ 7', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (84, '/pochvoobrabatyvayushhaya-tekhnika/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (85, '/pogruzchiki/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (86, '/polevye-raboty/!=', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (87, '/posevnaya-tekhnika/#5', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (88, '/premiksy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (89, '/pritsepy-i-polupritsepy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (90, '/probiotiki/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (91, '/prochaya-selskokhozyaystvennaya-tekhnika/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (92, '/prochee/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (93, '/prochie-korma/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (94, '/prod-oborudovanie/#%', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (95, '/produkty-bystrogo-prigotovleniya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (96, '/proizvodstvennye-predpriyatiya/$=', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (97, '/proizvodstvo-produktsii-pod-tm-zakazchika/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (98, '/pryanosti-pripravy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (99, '/rastitelnye-ekstrakty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (100, '/regulyatory-rosta/+H', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (101, '/remont-servisnoe-obsluzhivanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (102, '/ryba-moreprodukty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (103, '/rybnaya-muka/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (104, '/rybovodcheskie-khozyaystva-vodoemy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (105, '/sakhar/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (106, '/sanitarnaya-obrabotka/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (107, '/semena/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (108, '/seno-soloma/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (109, '/sistemy-orosheniya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (110, '/skh-zhivotnye-i-ptitsa/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (111, '/skladskie-uslugi/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (112, '/sklady/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (113, '/snekovaya-produktsiya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (114, '/soft-apk/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (115, '/sol-kormovaya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (116, '/solod/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (117, '/sousy-ketchup-mayonez/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (118, '/spetstekhnika/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (119, '/sredstva-dlya-dezinsektsii-i-deratizatsii/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (120, '/sredstva-zashhity-rasteniy/0U', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (121, '/strakhovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (122, '/stroitelstvo-agro/ ;', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (123, '/sushilnoe-oborudovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (124, '/tara-upakovka/)G', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (125, '/tekhnicheskie-kultury/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (126, '/tekhnicheskoe-syre/ =', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (127, '/tekhnika-dlya-khraneniya-zerna-v-rukavakh/''C', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (128, '/tekhnika-dlya-sadovodstva/+C', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (129, '/tekhnika-dlya-zhivotnovodstva/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (130, '/tekhnika-vneseniya-udobreniya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (131, '/teplitsy-obekty/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (132, '/toplivnye-materialy-iz-skh-otkhodov/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (133, '/tovary-pishheprom/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (134, '/traktory/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (135, '/uborka-urozhaya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (136, '/uborochnaya-tekhnika/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (137, '/uchebnye-tsentry/ H', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (138, '/udobreniya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (139, '/upakovochnye-materialy-i-syre/4', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (140, '/uslugi-agronoma/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (141, '/uslugi-avtomatizatsii/"7', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (142, '/uslugi-elevatora/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (143, '/uslugi-fasovki-upakovki-rozliva/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (144, '/uslugi-pererabotki-skh-syrya/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (145, '/uslugi-po-podgotovke-semyan/''=', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (146, '/uslugi-po-soderzhaniyu-skh-zhivotnykh/*G', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (147, '/uslugi-po-uboyu-i-pervichnoy-pererabotke/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (148, '/uslugi-po-vyrashhivaniyu-rassady/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (149, '/uslugi-veterinara/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (150, '/utilizatsiya-otkhodov/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (151, '/vesoizmeritelnoe-oborudovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (152, '/vitaminy/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (153, '/yaichnyy-poroshok/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (154, '/yaytso/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (155, '/zakvaski/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (156, '/zapchasti/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (157, '/zemelnye-uchastki/#7', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (158, '/zerno-furazhnoe/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (159, '/zerno/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (160, '/zernopererabatyvayushhee-oborudovanie/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (161, '/zhidkie-korma/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (162, '/zhmykh/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (163, '/ztsm/', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (164, 'V#E', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (165, 'infimum', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (166, 'p7654\210/.;- +* (''X%$#q"o', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (167, 'supremum', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (168, 'Авиахимработы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (169, 'Агрохимический анализ почвы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (170, 'Ангары и каркасно-тентовые конструкции', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (171, 'Аренда спецтехники', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (172, 'Барда, пивная дробина', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (173, 'Безалкогольные напитки, соки', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (174, 'Биопрепараты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (175, 'Блюда домашней кухни', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (176, 'Весоизмерительное оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (177, 'Витамины и аминокислоты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (178, 'Горюче-смазочные материалы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (179, 'Грибы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (180, 'Грузовой с/х транспорт', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (181, 'Грузоперевозки', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (182, 'Грунты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (183, 'Декоративные культуры', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (184, 'Для животноводства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (185, 'Для молочной промышленности', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (186, 'Для переработки овощей, фруктов, ягод', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (187, 'Для производства кормов', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (188, 'Для производства продуктов питания', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (189, 'Для растениеводства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (190, 'Емкостное оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (191, 'Жидкие корма', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (192, 'Жмых, шрот, жом, патока', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (193, 'Заменители молока', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (194, 'Замороженные овощи, фрукты, ягоды', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (195, 'Запчасти для сельхозтехники', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (196, 'Земельные участки с/х назначения', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (197, 'Зерно фуражное', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (198, 'Зерно, зернобобовые', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (199, 'Зерноперерабатывающее оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (200, 'Изоляты, концентраты, текстураты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (201, 'Инвестиции в с/х', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (202, 'Ингредиенты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (203, 'Информационные услуги', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (204, 'Книги, документация, аграрные издания', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (205, 'Комбикорма, зерносмеси', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (206, 'Кондитерские изделия', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (207, 'Консерванты и закваски для силосования', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (208, 'Консервированные продукты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (209, 'Корма для рыб', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (210, 'Корма экструдированные', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (211, 'Кормовые добавки', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (212, 'Кормовые дрожжи', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (213, 'Кормовые корнеплоды', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (214, 'Кормозаготовительная техника', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (215, 'Крахмало-паточная продукция', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (216, 'Крупы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (217, 'Макаронные изделия', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (218, 'Маркировочное и этикетировочное оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (219, 'Масличные культуры', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (220, 'Масложировая продукция', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (221, 'Микроудобрения', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (222, 'Минеральные удобрения', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (223, 'Мини-техника', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (224, 'Моечное и санитарно-гигиеническое оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (225, 'Молоко, молочные продукты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (226, 'Моющие и дезинфицирующие средства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (227, 'Мука', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (228, 'Мука кровяная', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (229, 'Мука мясная', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (230, 'Мука мясокостная', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (231, 'Мука перьевая', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (232, 'Мука рыбная', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (233, 'Мука травяная', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (234, 'Мясо и мясные продукты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (235, 'Мясоперерабатывающее оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (236, 'Мёд, продукция пчеловодства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (237, 'Навигационные и контрольные системы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (238, 'Некондиционные продукты питания на корм животным', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (239, 'Оборудование для переработки с/х отходов', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (240, 'Оборудование для производства упаковки', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (241, 'Оборудование для птицеводства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (242, 'Оборудование для пчеловодства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (243, 'Оборудование для рыбоводства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (244, 'Оборудование для складов и хранилищ', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (245, 'Оборудование для тракторов и сх транспорта', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (246, 'Оборудование прочее', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (247, 'Овощи', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (248, 'Опрыскиватели', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (249, 'Органические удобрения', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (250, 'Органоминеральные удобрения', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (251, 'Орехи', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (252, 'Отруби', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (253, 'Отруби пищевые', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (254, 'Пасты, пюре', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (255, 'Пеллеты, дрова, уголь', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (256, 'Перерабатывающие предприятия', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (257, 'Погрузчики', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (258, 'Посевная техника', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (259, 'Почвообрабатывающая техника', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (260, 'Премиксы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (261, 'Прицепы и полуприцепы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (262, 'Пробиотики', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (263, 'Программное обеспечение АПК', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (264, 'Продукты быстрого приготовления', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (265, 'Проектирование и строительство с/х объектов', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (266, 'Производственные предприятия', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (267, 'Производство продукции под ТМ заказчика', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (268, 'Прочая продукция', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (269, 'Прочая сельскохозяйственная техника', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (270, 'Прочая спецтехника', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (271, 'Прочее', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (272, 'Прочие корма', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (273, 'Пряности, приправы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (274, 'Различные товары для пищевой промышленности', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (275, 'Различные товары для сельского хозяйства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (276, 'Растительные экстракты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (277, 'Регуляторы роста', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (278, 'Ремонт и сервисное обслуживание', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (279, 'Рыба и морепродукты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (280, 'Рыбоводческие хозяйства, водоемы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (281, 'С/х животные и птица (живок)', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (282, 'С/х отходы и побочные продукты производства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (283, 'Санитарная обработка', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (284, 'Сахар', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (285, 'Сельский туризм', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (286, 'Семена, посевной материал', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (287, 'Сено, солома, силос', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (288, 'Складские услуги', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (289, 'Склады, хранилища, элеваторы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (290, 'Снековая продукция', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (291, 'Солод', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (292, 'Соль кормовая', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (293, 'Соусы, кетчуп, майонез', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (294, 'Средства для дезинсекции и дератизации', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (295, 'Средства защиты растений', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (296, 'Страхование с/х', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (297, 'Сушеные овощи и фрукты', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (298, 'Сушильное оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (299, 'Тара, упаковка', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (300, 'Теплицы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (301, 'Техника для внесения удобрения', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (302, 'Техника для животноводства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (303, 'Техника для полива и орошения', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (304, 'Техника для садоводства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (305, 'Техника для хранения зерна в рукавах', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (306, 'Технические культуры', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (307, 'Техническое сырье', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (308, 'Тракторы сельскохозяйственные', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (309, 'Уборочная техника', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (310, 'Упаковочное и фасовочное оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (311, 'Упаковочные материалы и сырье', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (312, 'Услуги агронома', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (313, 'Услуги ветеринара', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (314, 'Услуги переработки с/х сырья', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (315, 'Услуги по автоматизации и модернизации производства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (316, 'Услуги по выращиванию рассады', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (317, 'Услуги по подготовке семян', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (318, 'Услуги по содержанию с/х животных', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (319, 'Услуги по уборке урожая', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (320, 'Услуги по убою и первичной переработке', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (321, 'Услуги полевых работ', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (322, 'Услуги фасовки, упаковки, розлива', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (323, 'Услуги элеватора', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (324, 'Утилизация отходов', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (325, 'Учебные центры', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (326, 'Фермы', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (327, 'Фрукты. Ягоды', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (328, 'Хлебопекарное и кондитерское оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (329, 'Хозяйства', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (330, 'Холодильное оборудование', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (331, 'Чай, кофе, какао-порошок', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (332, 'Яичный порошок, меланж', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
INSERT INTO categories (id, name, parent_id, created_at, updated_at) VALUES (333, 'Яйцо', NULL, UNIX_TIMESTAMP(), UNIX_TIMESTAMP());
